# Site identity
title: Irene Voskamp
description: Strategy, Transformation, and Responsible AI

# Theme (keep these)
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme

# Top navigation (files must exist at repo root)
header_pages:
  - about.md
  - work.md
  - community.md
  - contact.md

# Make sure you have _layouts/page.html
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
