title: Irene Voskamp
description: Strategy, Transformation, and Responsible AI
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme 

# Add a top nav:
header_pages:
  - about.md
  - work.md
  - community.md
  - contact.md
